# Generated by Django 5.0.1 on 2024-01-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='division',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Barishal', 'Barishal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
