# Generated by Django 5.0.1 on 2024-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/media/profile_pics/'),
        ),
    ]
